[project]
name = "module02-vector-search"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Haneen Soliman", email = "148384474+haneens5905@users.noreply.github.com" }
]
requires-python = ">=3.12"
dependencies = [
    "jupyter>=1.1.1",
    "minsearch>=0.2.0",
    "openai>=2.45.0",
    "python-dotenv>=1.2.2",
    "requests>=2.34.2",
    "sentence-transformers>=5.6.1",
    "torch>=2.13.0",
]

[project.scripts]
module02-vector-search = "module02_vector_search:main"

[build-system]
requires = ["uv_build>=0.12.0,<0.13.0"]
build-backend = "uv_build"

[tool.uv.sources]
torch = [
  { index = "pytorch-cpu" },
]

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true
